package com.gsterling.press;
import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.util.DisplayMetrics;import android.view.View;import android.widget.*;
import java.util.*;
public class MainActivity extends Activity{
 TextView status,detail,current; Switch rotation; Button next;
 static final String[] N={"THE PURSUIT","INTO THE STORM","CANNON FIRE","THE GHOST FLEET","HIDDEN COVE","IN PORT","A NEW HORIZON"};
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);detail=findViewById(R.id.detail);current=findViewById(R.id.current);rotation=findViewById(R.id.rotation);next=findViewById(R.id.nextScene);rotation.setChecked(Prefs.rotation(this));show();findViewById(R.id.installTheme).setOnClickListener(v->install());next.setOnClickListener(v->advance());rotation.setOnCheckedChangeListener((x,on)->{Prefs.setRotation(this,on);Scheduler.schedule(this,on?Scheduler.Mode.DAILY:Scheduler.Mode.OFF);show();});findViewById(R.id.testRotation).setOnClickListener(v->{Prefs.setRotation(this,true);rotation.setChecked(true);Scheduler.schedule(this,Scheduler.Mode.TEST);Toast.makeText(this,"Test rotation armed for 5 minutes.",Toast.LENGTH_LONG).show();});}
 void install(){try{applyScene(this,Prefs.index(this));Prefs.setRotation(this,true);rotation.setChecked(true);Scheduler.schedule(this,Scheduler.Mode.DAILY);status.setText("BLACK TIDE INSTALLED ✓");detail.setText("Daily voyage armed for approximately 4:00 AM.");show();}catch(Exception e){status.setText("INSTALLATION NEEDS ATTENTION");detail.setText(String.valueOf(e.getMessage()));}}
 void advance(){int i=(Prefs.index(this)+1)%N.length;Prefs.setIndex(this,i);try{applyScene(this,i);show();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
 void show(){current.setText("CURRENT CHAPTER · DAY "+(Prefs.index(this)+1)+"\n"+N[Prefs.index(this)]);detail.setText(Prefs.rotation(this)?"Daily Rotation ON · approximately 4:00 AM":"Daily Rotation OFF");}
 static void applyScene(Context c,int i)throws Exception{String[] h={"black_tide_01_home","black_tide_02_home","black_tide_03_home","black_tide_04_home","black_tide_05_home","black_tide_06_home","black_tide_07_home"};String[] l={"black_tide_01_lock","black_tide_02_lock","black_tide_03_lock","black_tide_04_lock","black_tide_05_lock","black_tide_06_lock","black_tide_07_lock"};apply(c,h[i],WallpaperManager.FLAG_SYSTEM);apply(c,l[i],WallpaperManager.FLAG_LOCK);}
 static void apply(Context c,String n,int flag)throws Exception{int id=c.getResources().getIdentifier(n,"drawable",c.getPackageName());if(id==0)throw new IllegalStateException("BLACK TIDE master missing: "+n);Bitmap s=BitmapFactory.decodeResource(c.getResources(),id);DisplayMetrics dm=c.getResources().getDisplayMetrics();int w=dm.widthPixels,h=dm.heightPixels;float q=Math.max((float)w/s.getWidth(),(float)h/s.getHeight());int sw=Math.round(s.getWidth()*q),sh=Math.round(s.getHeight()*q);Bitmap z=Bitmap.createScaledBitmap(s,sw,sh,true);Bitmap p=Bitmap.createBitmap(z,Math.max(0,(sw-w)/2),Math.max(0,(sh-h)/2),Math.min(w,sw),Math.min(h,sh));WallpaperManager wm=WallpaperManager.getInstance(c);wm.suggestDesiredDimensions(w,h);wm.setBitmap(p,null,false,flag);if(p!=z)p.recycle();if(z!=s)z.recycle();s.recycle();}
}